project: SORS

method: bayes
metric:
  name: error_mean
  goal: minimize
run_cap: 10000

parameters:
  density:
    distribution: uniform
    min: 200
    max: 2000
  
  youngsModulus:
    distribution: uniform
    min: 100000
    max: 800000

  poissonsRatio:
    distribution: uniform
    min: 0.2
    max: 0.4999